openapi: 3.0.3
info:
  title: TravelAI API
  description: 엔터프라이즈 여행 큐레이션 앱을 위한 전체 API 명세서
  version: 1.0.0

servers:
  - url: https://api.travelai.com/v1

paths:
  /auth/signup:
    post:
      summary: 사용자 회원가입
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                name:
                  type: string
              required: [email, password, name]
      responses:
        '201':
          description: 회원가입 성공
        '400':
          description: 유효하지 않은 요청

  /auth/login:
    post:
      summary: 사용자 로그인
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: 인증 실패

  /auth/logout:
    post:
      summary: 사용자 로그아웃
      tags: [Auth]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 로그아웃 성공

  /auth/reset-password:
    post:
      summary: 비밀번호 재설정 요청
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required: [email]
      responses:
        '200':
          description: 재설정 이메일 발송됨

  /profile:
    get:
      summary: 사용자 프로필 조회
      tags: [Profile]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 프로필 정보 반환
    put:
      summary: 사용자 프로필 수정
      tags: [Profile]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                preferredLanguage:
                  type: string
                travelStyle:
                  type: string
      responses:
        '200':
          description: 수정 완료

  /curation/start:
    post:
      summary: 새 큐레이션 시작
      tags: [Curation]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 마법사 시작 응답 반환

  /curation/respond:
    post:
      summary: 큐레이션 질문 응답 저장
      tags: [Curation]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                questionId:
                  type: string
                answer:
                  type: string
              required: [questionId, answer]
      responses:
        '200':
          description: 응답 저장됨

  /curation/result:
    get:
      summary: 큐레이션 결과 조회
      tags: [Curation]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 추천 일정 및 명소 목록 반환

  /curation/history:
    get:
      summary: 사용자의 큐레이션 히스토리 조회
      tags: [Curation]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 저장된 큐레이션 목록 반환

  /prompt/save:
    post:
      summary: 프롬프트 저장
      tags: [Prompt]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                data:
                  type: object
              required: [name, data]
      responses:
        '200':
          description: 프롬프트 저장 성공

  /prompt/list:
    get:
      summary: 저장된 프롬프트 목록 조회
      tags: [Prompt]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 프롬프트 목록 반환

  /system/environment:
    get:
      summary: 사용자 위치/시간/날씨 정보 수집
      tags: [System]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 환경 정보 반환

  /alert/latest:
    get:
      summary: 최신 긴급 알림 조회
      tags: [Alert]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 최신 알림 데이터 반환

  /offline/data:
    get:
      summary: 오프라인 큐레이션 데이터 조회
      tags: [Offline]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: 캐시된 데이터 반환

  /translate:
    get:
      summary: AI 기반 텍스트 번역
      tags: [Translation]
      parameters:
        - name: text
          in: query
          required: true
          description: 번역할 원본 텍스트
          schema:
            type: string
        - name: from
          in: query
          required: false
          description: 원본 언어 코드 (예: 'auto', 'en', 'ja')
          schema:
            type: string
        - name: to
          in: query
          required: true
          description: 대상 언어 코드 (예: 'ko', 'en')
          schema:
            type: string
      responses:
        '200':
          description: 번역된 텍스트 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  translatedText:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
